# Generated by Django 6.0.7 on 2026-08-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginevent',
            name='device',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loginevent',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
