# Generated by Django 6.0.7 on 2026-07-29 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_sizechartrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityDiscountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_quantity', models.PositiveIntegerField(unique=True)),
                ('discount_percent', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'ordering': ['-min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='CategoryPriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_rule', to='catalog.sportcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FabricPriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_rule', to='catalog.fabric')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
