# Generated by Django 6.0.7 on 2026-08-18 00:20

import apps.core.storage
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('document', 'Legal document'), ('award', 'Award')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advergo/achievements/')),
                ('title', models.CharField(max_length=120)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('issuing_body', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=40)),
                ('routing_number', models.CharField(blank=True, max_length=30)),
                ('branch_name', models.CharField(blank=True, max_length=150)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="Use a line break to control where the red accent line starts, e.g. 'Built for champions.\\nMade your way.' -- the part after the break is highlighted red.", max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advergo/banners/')),
                ('cta_label', models.CharField(blank=True, max_length=40)),
                ('cta_href', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority wins when multiple banners are active.')),
                ('featured_from', models.DateTimeField(blank=True, null=True)),
                ('featured_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('logo_url', models.URLField(blank=True)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='advergo/clients/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_alt', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=150)),
                ('head_office', models.CharField(blank=True, max_length=250)),
                ('factory', models.CharField(blank=True, max_length=250)),
                ('founded', models.CharField(blank=True, max_length=10)),
                ('md', models.CharField(blank=True, max_length=120)),
                ('chairman', models.CharField(blank=True, max_length=120)),
                ('trade_license_no', models.CharField(blank=True, max_length=60)),
                ('signature_image', models.ImageField(blank=True, help_text='Authorized signature/stamp -- printed on generated documents (Chalan, etc.) above the `md` name. Falls back to a blank signature line if unset.', null=True, upload_to='advergo/company/')),
                ('about', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'company info',
                'verbose_name_plural': 'company info',
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(blank=True, help_text='Emoji shown in the UI.', max_length=8)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'gallery categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HomeSectionBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('ready_products', 'Ready Products'), ('category_showcase', 'Category Showcase'), ('design_collection', 'Design Collection')], max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advergo/section_banners/')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('href', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='MobileBankingAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(help_text='e.g. bKash, Nagad', max_length=40)),
                ('agent_number', models.CharField(max_length=20)),
                ('label', models.CharField(blank=True, help_text='e.g. Agent, Merchant', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'provider'],
            },
        ),
        migrations.CreateModel(
            name='OfficialDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('trade_license', 'Trade License'), ('tin', 'TIN Certificate'), ('bin', 'BIN Certificate'), ('incorporation', 'Certificate of Incorporation')], max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, storage=apps.core.storage.get_raw_file_storage, upload_to='advergo/official_documents/')),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['doc_type'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='advergo/team/')),
                ('bio', models.TextField(blank=True, help_text='Leadership quote/bio; usually blank for staff.')),
                ('is_leadership', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advergo/gallery/')),
                ('label', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery_items', to='content.gallerycategory')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
