# Generated by Django 6.0.7 on 2026-07-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(help_text="Use a line break to control where the red accent line starts, e.g. 'Built for champions.\\nMade your way.' -- the part after the break is highlighted red.", max_length=150),
        ),
    ]
