# Generated by Django 6.0.7 on 2026-08-16 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSectionBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('ready_products', 'Ready Products'), ('category_showcase', 'Category Showcase'), ('design_collection', 'Design Collection')], max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advergo/section_banners/')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('href', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section'],
            },
        ),
    ]
