# Generated by Django 6.0.7 on 2026-07-31 16:44

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_banner_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=40)),
                ('routing_number', models.CharField(blank=True, max_length=30)),
                ('branch_name', models.CharField(blank=True, max_length=150)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='MobileBankingAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(help_text='e.g. bKash, Nagad', max_length=40)),
                ('agent_number', models.CharField(max_length=20)),
                ('label', models.CharField(blank=True, help_text='e.g. Agent, Merchant', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'provider'],
            },
        ),
        migrations.CreateModel(
            name='OfficialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('trade_license', 'Trade License'), ('tin', 'TIN Certificate'), ('bin', 'BIN Certificate'), ('incorporation', 'Certificate of Incorporation')], max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, storage=apps.core.storage.get_raw_file_storage, upload_to='official_documents/')),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['doc_type'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('bio', models.TextField(blank=True, help_text='Leadership quote/bio; usually blank for staff.')),
                ('is_leadership', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='clientlogo',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='trade_license_no',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
    ]
