# Generated by Django 6.0.7 on 2026-08-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_homesectionbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Authorized signature/stamp -- printed on generated documents (Chalan, etc.) above the `md` name. Falls back to a blank signature line if unset.', null=True, upload_to='advergo/company/'),
        ),
    ]
