# Generated by Django 6.0.7 on 2026-08-18 00:20

import apps.core.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chalan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chalan_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, storage=apps.core.storage.get_raw_file_storage, upload_to='advergo/chalans/')),
                ('include_price', models.BooleanField(default=False, help_text='Whether this copy states unit price / total value.')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, storage=apps.core.storage.get_raw_file_storage, upload_to='advergo/invoices/')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, storage=apps.core.storage.get_raw_file_storage, upload_to='advergo/quotations/')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
