# Generated by Django 6.0.7 on 2026-07-29 11:15

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=apps.core.storage.get_raw_file_storage, upload_to='invoices/'),
        ),
    ]
