# Generated by Django 6.0.7 on 2026-08-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='avatar',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='advergo/avatars/'),
        ),
    ]
