# Generated by Django 6.0.7 on 2026-07-29 10:22

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_sizechartrow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('quantity', models.PositiveIntegerField()),
                ('size_breakdown', models.CharField(blank=True, help_text='e.g. 5xS, 10xM, 8xL, 2xXL', max_length=300)),
                ('design_file', models.FileField(blank=True, null=True, upload_to='quotes/', validators=[apps.core.validators.validate_design_file])),
                ('notes', models.TextField(blank=True)),
                ('estimated_price_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_price_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('quoted', 'Quoted'), ('converted', 'Converted to order'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal only -- never shown to the customer.')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='catalog.sportcategory')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='catalog.fabric')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='catalog.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
