# Generated by Django 6.0.7 on 2026-09-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquoterequest',
            name='custom_product_name',
            field=models.CharField(blank=True, help_text="For an item that isn't in the catalog -- typically an order taken by phone/WhatsApp/inbox. Shown on the quotation PDF instead of a catalog product when set; leave blank when `product` above is used instead.", max_length=150),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='custom_product_name',
            field=models.CharField(blank=True, help_text="For an item that isn't in the catalog -- typically an order taken by phone/WhatsApp/inbox. Shown on the quotation PDF instead of a catalog product when set; leave blank when `product` above is used instead.", max_length=150),
        ),
    ]
