# Generated by Django 6.0.7 on 2026-08-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quoterequest_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Firm negotiated price staff enters before generating a formal Quotation PDF. Leave blank to have the PDF print the estimated range instead.', max_digits=10, null=True),
        ),
    ]
