# Generated by Django 6.0.7 on 2026-08-16 23:42

import apps.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('quotes', '0003_quoterequest_quoted_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalQuoteRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('reference_code', models.CharField(db_index=True, editable=False, max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('quantity', models.PositiveIntegerField()),
                ('size_breakdown', models.CharField(blank=True, help_text='e.g. 5xS, 10xM, 8xL, 2xXL', max_length=300)),
                ('delivery_address', models.TextField(blank=True, help_text='Where the finished order should be delivered.')),
                ('design_file', models.TextField(blank=True, max_length=100, null=True, validators=[apps.core.validators.validate_design_file])),
                ('notes', models.TextField(blank=True)),
                ('estimated_price_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_price_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Firm negotiated price staff enters before generating a formal Quotation PDF. Leave blank to have the PDF print the estimated range instead.', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('quoted', 'Quoted'), ('converted', 'Converted to order'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal only -- never shown to the customer.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.category')),
                ('design', models.ForeignKey(blank=True, db_constraint=False, help_text='Set when the customer picked a design from the catalog instead of uploading their own design_file.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.design')),
                ('fabric', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.fabric')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.product')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical quote request',
                'verbose_name_plural': 'historical quote requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
