# Generated by Django 6.0.7 on 2026-08-16 12:54

import apps.catalog.models
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('grade', models.CharField(blank=True, max_length=80)),
                ('best_for', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advergo/fabrics/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.catalog.models.category_image_upload_path)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Shown on the homepage. Every category is listed on /categories regardless.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, help_text='Leave blank for a top-level category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('code', models.CharField(blank=True, help_text='Internal reference code shown to staff/customers.', max_length=40)),
                ('image', models.ImageField(upload_to=apps.catalog.models.design_upload_path)),
                ('is_active', models.BooleanField(default=True, help_text='Unpublish without deleting.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('price_range', models.CharField(blank=True, max_length=60)),
                ('fabric', models.CharField(blank=True, help_text='Free-text fabric label shown on the card.', max_length=150)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('accent_color', models.CharField(default='#eb2127', help_text='Hex color, e.g. #eb2127.', max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advergo/products/')),
                ('is_featured', models.BooleanField(default=False, help_text='Shown in the homepage featured-products section.')),
                ('is_active', models.BooleanField(default=True, help_text='Unpublish without deleting.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SizeChartRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size_label', models.CharField(help_text='e.g. S, M, L, XL, XXL', max_length=10)),
                ('chest_in', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='chest (in)')),
                ('length_in', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='length (in)')),
                ('shoulder_in', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='shoulder (in)')),
                ('sleeve_in', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='sleeve (in)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, help_text='Leave blank for a general chart shown regardless of category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_chart_rows', to='catalog.category')),
            ],
            options={
                'ordering': ['category_id', 'order'],
            },
        ),
    ]
