# Generated by Django 6.0.7 on 2026-07-29 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeChartRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size_label', models.CharField(help_text='e.g. S, M, L, XL, XXL', max_length=10)),
                ('chest_in', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='chest (in)')),
                ('length_in', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='length (in)')),
                ('shoulder_in', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='shoulder (in)')),
                ('sleeve_in', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='sleeve (in)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, help_text='Leave blank for a general chart shown regardless of category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_chart_rows', to='catalog.sportcategory')),
            ],
            options={
                'ordering': ['category_id', 'order'],
            },
        ),
    ]
