# Generated by Django 6.0.7 on 2026-08-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizechartrow',
            options={'ordering': ['category_id', 'age_group', 'order']},
        ),
        migrations.RemoveField(
            model_name='sizechartrow',
            name='shoulder_in',
        ),
        migrations.RemoveField(
            model_name='sizechartrow',
            name='sleeve_in',
        ),
        migrations.AddField(
            model_name='sizechartrow',
            name='age_group',
            field=models.CharField(choices=[('adult', 'Adult'), ('kids', 'Kids')], default='adult', help_text='Which size chart tab this row belongs to.', max_length=5),
        ),
    ]
