# Generated by Django 6.0.7 on 2026-09-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage shown on the product card, e.g. 15.00.', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Regular/original price before discount.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted selling price shown to customers.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_range',
            field=models.CharField(blank=True, help_text='Legacy price text shown in some sections; prefer sale_price + list_price for discounts.', max_length=60),
        ),
    ]
