# Generated by Django 6.0.7 on 2026-09-02 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_discount_percent_product_list_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='advergo/fabrics/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.fabric')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
