# Generated by Django 6.0.7 on 2026-09-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_catalog_staff_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Ready product',
                'verbose_name_plural': 'Ready products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='ShowcaseProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Showcase product',
                'verbose_name_plural': 'Showcase products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='age_group',
            field=models.CharField(choices=[('adult', 'Adult'), ('kids', 'Kids')], default='adult', help_text='Storefront Adult/Kids filter for Ready Products.', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('ready', 'Ready product'), ('showcase', 'Showcase (made-to-order example)')], default='ready', help_text='Ready products are priced and shown with Add to Cart. Showcase products are made-to-order examples with no price -- managed from their own admin screens (Ready Products / Showcase Products), not edited here directly.', max_length=10),
        ),
    ]
