# Generated by Django 6.0.7 on 2026-09-05 12:40

import apps.core.models
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_backfill_product_type"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="design",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", apps.core.models.SoftDeleteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="fabric",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", apps.core.models.SoftDeleteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="product",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", apps.core.models.SoftDeleteManager()),
            ],
        ),
    ]
